// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMembershipByUserAndOrg = `-- name: GetMembershipByUserAndOrg :one
SELECT
  uo.id,
  uo.user_id,
  uo.organization_id,
  uo.role_id,
  uo.is_default,
  o.name AS organization_name,
  r.name AS role_name
FROM user_organizations uo
JOIN organizations o ON o.id = uo.organization_id
JOIN custom_roles r ON r.id = uo.role_id
WHERE uo.user_id = $1::uuid
  AND uo.organization_id = $2::uuid
  AND uo.deleted_at IS NULL
  AND o.deleted_at IS NULL
  AND r.deleted_at IS NULL
`

type GetMembershipByUserAndOrgParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetMembershipByUserAndOrgRow struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	RoleID           uuid.UUID `json:"role_id"`
	IsDefault        bool      `json:"is_default"`
	OrganizationName string    `json:"organization_name"`
	RoleName         string    `json:"role_name"`
}

func (q *Queries) GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (GetMembershipByUserAndOrgRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserAndOrg, arg.UserID, arg.OrganizationID)
	var i GetMembershipByUserAndOrgRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.RoleID,
		&i.IsDefault,
		&i.OrganizationName,
		&i.RoleName,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, avatar_url, is_active, is_super_admin, availability_status, settings, last_login
FROM users
WHERE email = $1::text
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	FullName           string             `json:"full_name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	IsActive           bool               `json:"is_active"`
	IsSuperAdmin       bool               `json:"is_super_admin"`
	AvailabilityStatus string             `json:"availability_status"`
	Settings           []byte             `json:"settings"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsSuperAdmin,
		&i.AvailabilityStatus,
		&i.Settings,
		&i.LastLogin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, avatar_url, is_active, is_super_admin, availability_status, settings, last_login
FROM users
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	FullName           string             `json:"full_name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	IsActive           bool               `json:"is_active"`
	IsSuperAdmin       bool               `json:"is_super_admin"`
	AvailabilityStatus string             `json:"availability_status"`
	Settings           []byte             `json:"settings"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.IsSuperAdmin,
		&i.AvailabilityStatus,
		&i.Settings,
		&i.LastLogin,
	)
	return i, err
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT
  uo.id,
  uo.user_id,
  uo.organization_id,
  uo.role_id,
  uo.is_default,
  o.name AS organization_name,
  r.name AS role_name
FROM user_organizations uo
JOIN organizations o ON o.id = uo.organization_id
JOIN custom_roles r ON r.id = uo.role_id
WHERE uo.user_id = $1::uuid
  AND uo.deleted_at IS NULL
  AND o.deleted_at IS NULL
  AND r.deleted_at IS NULL
ORDER BY uo.is_default DESC, o.name ASC
`

type ListUserMembershipsRow struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	RoleID           uuid.UUID `json:"role_id"`
	IsDefault        bool      `json:"is_default"`
	OrganizationName string    `json:"organization_name"`
	RoleName         string    `json:"role_name"`
}

func (q *Queries) ListUserMemberships(ctx context.Context, userID uuid.UUID) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.RoleID,
			&i.IsDefault,
			&i.OrganizationName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvailability = `-- name: UpdateUserAvailability :exec
UPDATE users
SET availability_status = $1::text, updated_at = now()
WHERE id = $2::uuid
`

type UpdateUserAvailabilityParams struct {
	AvailabilityStatus string    `json:"availability_status"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserAvailability(ctx context.Context, arg UpdateUserAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateUserAvailability, arg.AvailabilityStatus, arg.ID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = now(), updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :exec
UPDATE users
SET settings = $1::jsonb, updated_at = now()
WHERE id = $2::uuid
`

type UpdateUserSettingsParams struct {
	Settings []byte    `json:"settings"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserSettings, arg.Settings, arg.ID)
	return err
}
