// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVisibleChatByID = `-- name: GetVisibleChatByID :one
SELECT
  c.id,
  c.name,
  c.phone_number,
  c.status,
  c.last_message_preview,
  c.last_message_at,
  c.instance_id,
  wi.name AS instance_name,
  COALESCE(cus.is_hidden, false) AS is_hidden,
  COALESCE(cus.is_pinned, false) AS is_pinned
FROM contacts c
LEFT JOIN whatsapp_instances wi ON wi.id = c.instance_id
LEFT JOIN contact_user_states cus
  ON cus.contact_id = c.id
 AND cus.user_id = $1::uuid
WHERE c.organization_id = $2::uuid
  AND c.id = $3::uuid
  AND c.deleted_at IS NULL
  AND (
    $4::text = 'all_contacts'
    OR (
      $4::text = 'instances_only'
      AND c.instance_id IS NOT NULL
      AND c.instance_id::text IN (
        SELECT jsonb_array_elements_text($5::jsonb)
      )
    )
    OR (
      $4::text = 'allowed_numbers_only'
      AND c.phone_number IN (
        SELECT jsonb_array_elements_text($6::jsonb)
      )
    )
    OR (
      $4::text = 'instances_plus_allowed_numbers'
      AND (
        (
          c.instance_id IS NOT NULL
          AND c.instance_id::text IN (
            SELECT jsonb_array_elements_text($5::jsonb)
          )
        )
        OR c.phone_number IN (
          SELECT jsonb_array_elements_text($6::jsonb)
        )
      )
    )
  )
`

type GetVisibleChatByIDParams struct {
	ViewerUserID        uuid.UUID `json:"viewer_user_id"`
	OrganizationID      uuid.UUID `json:"organization_id"`
	ContactID           uuid.UUID `json:"contact_id"`
	ScopeMode           string    `json:"scope_mode"`
	AllowedInstanceIds  []byte    `json:"allowed_instance_ids"`
	AllowedPhoneNumbers []byte    `json:"allowed_phone_numbers"`
}

type GetVisibleChatByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               pgtype.Text        `json:"name"`
	PhoneNumber        string             `json:"phone_number"`
	Status             string             `json:"status"`
	LastMessagePreview pgtype.Text        `json:"last_message_preview"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	InstanceName       pgtype.Text        `json:"instance_name"`
	IsHidden           bool               `json:"is_hidden"`
	IsPinned           bool               `json:"is_pinned"`
}

func (q *Queries) GetVisibleChatByID(ctx context.Context, arg GetVisibleChatByIDParams) (GetVisibleChatByIDRow, error) {
	row := q.db.QueryRow(ctx, getVisibleChatByID,
		arg.ViewerUserID,
		arg.OrganizationID,
		arg.ContactID,
		arg.ScopeMode,
		arg.AllowedInstanceIds,
		arg.AllowedPhoneNumbers,
	)
	var i GetVisibleChatByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Status,
		&i.LastMessagePreview,
		&i.LastMessageAt,
		&i.InstanceID,
		&i.InstanceName,
		&i.IsHidden,
		&i.IsPinned,
	)
	return i, err
}

const listMessagesByContact = `-- name: ListMessagesByContact :many
SELECT id, contact_id, direction, type, body, status, created_at, sent_by_user_id
FROM messages
WHERE organization_id = $1::uuid
  AND contact_id = $2::uuid
ORDER BY created_at ASC
`

type ListMessagesByContactParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ContactID      uuid.UUID `json:"contact_id"`
}

type ListMessagesByContactRow struct {
	ID           uuid.UUID          `json:"id"`
	ContactID    uuid.UUID          `json:"contact_id"`
	Direction    string             `json:"direction"`
	Type         string             `json:"type"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SentByUserID pgtype.UUID        `json:"sent_by_user_id"`
}

func (q *Queries) ListMessagesByContact(ctx context.Context, arg ListMessagesByContactParams) ([]ListMessagesByContactRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByContact, arg.OrganizationID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByContactRow
	for rows.Next() {
		var i ListMessagesByContactRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Direction,
			&i.Type,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.SentByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByContact = `-- name: ListNotesByContact :many
SELECT
  n.id,
  n.contact_id,
  n.author_user_id,
  n.body,
  n.created_at,
  u.full_name AS author_name
FROM conversation_notes n
JOIN users u ON u.id = n.author_user_id
WHERE n.organization_id = $1::uuid
  AND n.contact_id = $2::uuid
ORDER BY n.created_at ASC
`

type ListNotesByContactParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ContactID      uuid.UUID `json:"contact_id"`
}

type ListNotesByContactRow struct {
	ID           uuid.UUID          `json:"id"`
	ContactID    uuid.UUID          `json:"contact_id"`
	AuthorUserID uuid.UUID          `json:"author_user_id"`
	Body         string             `json:"body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AuthorName   string             `json:"author_name"`
}

func (q *Queries) ListNotesByContact(ctx context.Context, arg ListNotesByContactParams) ([]ListNotesByContactRow, error) {
	rows, err := q.db.Query(ctx, listNotesByContact, arg.OrganizationID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesByContactRow
	for rows.Next() {
		var i ListNotesByContactRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleChats = `-- name: ListVisibleChats :many
SELECT
  c.id,
  c.name,
  c.phone_number,
  c.status,
  c.last_message_preview,
  c.last_message_at,
  c.instance_id,
  wi.name AS instance_name,
  COALESCE(cus.is_hidden, false) AS is_hidden,
  COALESCE(cus.is_pinned, false) AS is_pinned
FROM contacts c
LEFT JOIN whatsapp_instances wi ON wi.id = c.instance_id
LEFT JOIN contact_user_states cus
  ON cus.contact_id = c.id
 AND cus.user_id = $1::uuid
WHERE c.organization_id = $2::uuid
  AND c.deleted_at IS NULL
  AND (
    $3::text = 'all_contacts'
    OR (
      $3::text = 'instances_only'
      AND c.instance_id IS NOT NULL
      AND c.instance_id::text IN (
        SELECT jsonb_array_elements_text($4::jsonb)
      )
    )
    OR (
      $3::text = 'allowed_numbers_only'
      AND c.phone_number IN (
        SELECT jsonb_array_elements_text($5::jsonb)
      )
    )
    OR (
      $3::text = 'instances_plus_allowed_numbers'
      AND (
        (
          c.instance_id IS NOT NULL
          AND c.instance_id::text IN (
            SELECT jsonb_array_elements_text($4::jsonb)
          )
        )
        OR c.phone_number IN (
          SELECT jsonb_array_elements_text($5::jsonb)
        )
      )
    )
  )
  AND ($6::bool OR c.status <> 'pending')
  AND (
    $7::text = ''
    OR COALESCE(c.name, '') ILIKE '%' || $7 || '%'
    OR c.phone_number ILIKE '%' || $7 || '%'
  )
ORDER BY COALESCE(cus.is_pinned, false) DESC, COALESCE(c.last_message_at, c.created_at) DESC
`

type ListVisibleChatsParams struct {
	ViewerUserID        uuid.UUID `json:"viewer_user_id"`
	OrganizationID      uuid.UUID `json:"organization_id"`
	ScopeMode           string    `json:"scope_mode"`
	AllowedInstanceIds  []byte    `json:"allowed_instance_ids"`
	AllowedPhoneNumbers []byte    `json:"allowed_phone_numbers"`
	IncludePending      bool      `json:"include_pending"`
	Search              string    `json:"search"`
}

type ListVisibleChatsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               pgtype.Text        `json:"name"`
	PhoneNumber        string             `json:"phone_number"`
	Status             string             `json:"status"`
	LastMessagePreview pgtype.Text        `json:"last_message_preview"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	InstanceName       pgtype.Text        `json:"instance_name"`
	IsHidden           bool               `json:"is_hidden"`
	IsPinned           bool               `json:"is_pinned"`
}

func (q *Queries) ListVisibleChats(ctx context.Context, arg ListVisibleChatsParams) ([]ListVisibleChatsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleChats,
		arg.ViewerUserID,
		arg.OrganizationID,
		arg.ScopeMode,
		arg.AllowedInstanceIds,
		arg.AllowedPhoneNumbers,
		arg.IncludePending,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleChatsRow
	for rows.Next() {
		var i ListVisibleChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Status,
			&i.LastMessagePreview,
			&i.LastMessageAt,
			&i.InstanceID,
			&i.InstanceName,
			&i.IsHidden,
			&i.IsPinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
