// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	PhoneNumber        string             `json:"phone_number"`
	Name               pgtype.Text        `json:"name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	AssignedUserID     pgtype.UUID        `json:"assigned_user_id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	Status             string             `json:"status"`
	LastMessagePreview pgtype.Text        `json:"last_message_preview"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	Tags               []byte             `json:"tags"`
	Metadata           []byte             `json:"metadata"`
}

type ContactUserState struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	ContactID         uuid.UUID          `json:"contact_id"`
	UserID            uuid.UUID          `json:"user_id"`
	IsHidden          bool               `json:"is_hidden"`
	IsPinned          bool               `json:"is_pinned"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ConversationNote struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ContactID      uuid.UUID          `json:"contact_id"`
	AuthorUserID   uuid.UUID          `json:"author_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Body           string             `json:"body"`
}

type CustomRole struct {
	ID                         uuid.UUID          `json:"id"`
	OrganizationID             uuid.UUID          `json:"organization_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	Name                       string             `json:"name"`
	Description                string             `json:"description"`
	IsSystem                   bool               `json:"is_system"`
	IsDefault                  bool               `json:"is_default"`
	DefaultScopeMode           string             `json:"default_scope_mode"`
	DefaultAllowedInstanceIds  []byte             `json:"default_allowed_instance_ids"`
	DefaultAllowedPhoneNumbers []byte             `json:"default_allowed_phone_numbers"`
	CanViewUnmaskedPhone       bool               `json:"can_view_unmasked_phone"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ContactID      uuid.UUID          `json:"contact_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Direction      string             `json:"direction"`
	Type           string             `json:"type"`
	Body           string             `json:"body"`
	Status         string             `json:"status"`
	SentByUserID   pgtype.UUID        `json:"sent_by_user_id"`
	Metadata       []byte             `json:"metadata"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	Timezone  string             `json:"timezone"`
	IsActive  bool               `json:"is_active"`
	Settings  []byte             `json:"settings"`
}

type OrganizationConfig struct {
	ID                          uuid.UUID          `json:"id"`
	OrganizationID              uuid.UUID          `json:"organization_id"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	TenantStatus                string             `json:"tenant_status"`
	StorageQuotaBytes           int64              `json:"storage_quota_bytes"`
	StorageUsedBytes            int64              `json:"storage_used_bytes"`
	UploadsCleanupRetentionDays int32              `json:"uploads_cleanup_retention_days"`
	UploadsCleanupHour          int16              `json:"uploads_cleanup_hour"`
	UploadsCleanupTimezone      pgtype.Text        `json:"uploads_cleanup_timezone"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Key         string    `json:"key"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Label       string    `json:"label"`
	Description string    `json:"description"`
}

type RolePermission struct {
	CustomRoleID uuid.UUID `json:"custom_role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	FullName           string             `json:"full_name"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	IsActive           bool               `json:"is_active"`
	IsSuperAdmin       bool               `json:"is_super_admin"`
	AvailabilityStatus string             `json:"availability_status"`
	Settings           []byte             `json:"settings"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
}

type UserContactVisibilityRule struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	UserID               uuid.UUID          `json:"user_id"`
	ScopeMode            string             `json:"scope_mode"`
	AllowedInstanceIds   []byte             `json:"allowed_instance_ids"`
	AllowedPhoneNumbers  []byte             `json:"allowed_phone_numbers"`
	InheritRoleScope     bool               `json:"inherit_role_scope"`
	CanViewUnmaskedPhone bool               `json:"can_view_unmasked_phone"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type UserOrganization struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	RoleID         uuid.UUID          `json:"role_id"`
	IsDefault      bool               `json:"is_default"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type UserPermissionOverride struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	PermissionKey  string             `json:"permission_key"`
	Mode           string             `json:"mode"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WhatsappInstance struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Name           string             `json:"name"`
	PhoneNumber    string             `json:"phone_number"`
	Status         string             `json:"status"`
	SourceLabel    pgtype.Text        `json:"source_label"`
}
