// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) (CustomRole, error)
	DeleteRolePermissionsByRole(ctx context.Context, customRoleID uuid.UUID) error
	DeleteUserPermissionOverrides(ctx context.Context, arg DeleteUserPermissionOverridesParams) error
	GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (GetMembershipByUserAndOrgRow, error)
	GetPermissionsByKeys(ctx context.Context, keys []string) ([]Permission, error)
	GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (CustomRole, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserVisibilityRule(ctx context.Context, arg GetUserVisibilityRuleParams) (UserContactVisibilityRule, error)
	GetVisibleChatByID(ctx context.Context, arg GetVisibleChatByIDParams) (GetVisibleChatByIDRow, error)
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error
	InsertUserPermissionOverride(ctx context.Context, arg InsertUserPermissionOverrideParams) error
	ListMessagesByContact(ctx context.Context, arg ListMessagesByContactParams) ([]ListMessagesByContactRow, error)
	ListNotesByContact(ctx context.Context, arg ListNotesByContactParams) ([]ListNotesByContactRow, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRolePermissionKeys(ctx context.Context, customRoleID uuid.UUID) ([]string, error)
	ListRoles(ctx context.Context, organizationID uuid.UUID) ([]CustomRole, error)
	ListUserMemberships(ctx context.Context, userID uuid.UUID) ([]ListUserMembershipsRow, error)
	ListUserPermissionOverrides(ctx context.Context, arg ListUserPermissionOverridesParams) ([]ListUserPermissionOverridesRow, error)
	ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListUsersByOrganizationRow, error)
	ListVisibleChats(ctx context.Context, arg ListVisibleChatsParams) ([]ListVisibleChatsRow, error)
	SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (CustomRole, error)
	UpdateUserAvailability(ctx context.Context, arg UpdateUserAvailabilityParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error
	UpsertUserVisibilityRule(ctx context.Context, arg UpsertUserVisibilityRuleParams) (UserContactVisibilityRule, error)
}

var _ Querier = (*Queries)(nil)
