// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO custom_roles (
  organization_id,
  name,
  description,
  is_system,
  is_default,
  default_scope_mode,
  default_allowed_instance_ids,
  default_allowed_phone_numbers,
  can_view_unmasked_phone
) VALUES (
  $1::uuid,
  $2::text,
  $3::text,
  $4::bool,
  $5::bool,
  $6::text,
  $7::jsonb,
  $8::jsonb,
  $9::bool
)
RETURNING id, organization_id, created_at, updated_at, deleted_at, name, description, is_system, is_default,
          default_scope_mode, default_allowed_instance_ids, default_allowed_phone_numbers, can_view_unmasked_phone
`

type CreateRoleParams struct {
	OrganizationID             uuid.UUID `json:"organization_id"`
	Name                       string    `json:"name"`
	Description                string    `json:"description"`
	IsSystem                   bool      `json:"is_system"`
	IsDefault                  bool      `json:"is_default"`
	DefaultScopeMode           string    `json:"default_scope_mode"`
	DefaultAllowedInstanceIds  []byte    `json:"default_allowed_instance_ids"`
	DefaultAllowedPhoneNumbers []byte    `json:"default_allowed_phone_numbers"`
	CanViewUnmaskedPhone       bool      `json:"can_view_unmasked_phone"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CustomRole, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.IsDefault,
		arg.DefaultScopeMode,
		arg.DefaultAllowedInstanceIds,
		arg.DefaultAllowedPhoneNumbers,
		arg.CanViewUnmaskedPhone,
	)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.DefaultScopeMode,
		&i.DefaultAllowedInstanceIds,
		&i.DefaultAllowedPhoneNumbers,
		&i.CanViewUnmaskedPhone,
	)
	return i, err
}

const deleteRolePermissionsByRole = `-- name: DeleteRolePermissionsByRole :exec
DELETE FROM role_permissions
WHERE custom_role_id = $1::uuid
`

func (q *Queries) DeleteRolePermissionsByRole(ctx context.Context, customRoleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionsByRole, customRoleID)
	return err
}

const getPermissionsByKeys = `-- name: GetPermissionsByKeys :many
SELECT id, key, resource, action, label, description
FROM permissions
WHERE key = ANY($1::text[])
ORDER BY key
`

func (q *Queries) GetPermissionsByKeys(ctx context.Context, keys []string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Resource,
			&i.Action,
			&i.Label,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, organization_id, created_at, updated_at, deleted_at, name, description, is_system, is_default,
       default_scope_mode, default_allowed_instance_ids, default_allowed_phone_numbers, can_view_unmasked_phone
FROM custom_roles
WHERE id = $1::uuid
  AND organization_id = $2::uuid
  AND deleted_at IS NULL
`

type GetRoleByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (CustomRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, arg.ID, arg.OrganizationID)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.DefaultScopeMode,
		&i.DefaultAllowedInstanceIds,
		&i.DefaultAllowedPhoneNumbers,
		&i.CanViewUnmaskedPhone,
	)
	return i, err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (custom_role_id, permission_id)
VALUES ($1::uuid, $2::uuid)
ON CONFLICT DO NOTHING
`

type InsertRolePermissionParams struct {
	CustomRoleID uuid.UUID `json:"custom_role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.CustomRoleID, arg.PermissionID)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, resource, action, label, description
FROM permissions
ORDER BY resource, key
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Resource,
			&i.Action,
			&i.Label,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionKeys = `-- name: ListRolePermissionKeys :many
SELECT p.key
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.custom_role_id = $1::uuid
ORDER BY p.key
`

func (q *Queries) ListRolePermissionKeys(ctx context.Context, customRoleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissionKeys, customRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, organization_id, created_at, updated_at, deleted_at, name, description, is_system, is_default,
       default_scope_mode, default_allowed_instance_ids, default_allowed_phone_numbers, can_view_unmasked_phone
FROM custom_roles
WHERE organization_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListRoles(ctx context.Context, organizationID uuid.UUID) ([]CustomRole, error) {
	rows, err := q.db.Query(ctx, listRoles, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomRole
	for rows.Next() {
		var i CustomRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.IsDefault,
			&i.DefaultScopeMode,
			&i.DefaultAllowedInstanceIds,
			&i.DefaultAllowedPhoneNumbers,
			&i.CanViewUnmaskedPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE custom_roles
SET deleted_at = now(), updated_at = now()
WHERE id = $1::uuid
  AND organization_id = $2::uuid
  AND is_system = false
`

type SoftDeleteRoleParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error {
	_, err := q.db.Exec(ctx, softDeleteRole, arg.ID, arg.OrganizationID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE custom_roles
SET
  name = $1::text,
  description = $2::text,
  default_scope_mode = $3::text,
  default_allowed_instance_ids = $4::jsonb,
  default_allowed_phone_numbers = $5::jsonb,
  can_view_unmasked_phone = $6::bool,
  updated_at = now()
WHERE id = $7::uuid
  AND organization_id = $8::uuid
RETURNING id, organization_id, created_at, updated_at, deleted_at, name, description, is_system, is_default,
          default_scope_mode, default_allowed_instance_ids, default_allowed_phone_numbers, can_view_unmasked_phone
`

type UpdateRoleParams struct {
	Name                       string    `json:"name"`
	Description                string    `json:"description"`
	DefaultScopeMode           string    `json:"default_scope_mode"`
	DefaultAllowedInstanceIds  []byte    `json:"default_allowed_instance_ids"`
	DefaultAllowedPhoneNumbers []byte    `json:"default_allowed_phone_numbers"`
	CanViewUnmaskedPhone       bool      `json:"can_view_unmasked_phone"`
	ID                         uuid.UUID `json:"id"`
	OrganizationID             uuid.UUID `json:"organization_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (CustomRole, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.DefaultScopeMode,
		arg.DefaultAllowedInstanceIds,
		arg.DefaultAllowedPhoneNumbers,
		arg.CanViewUnmaskedPhone,
		arg.ID,
		arg.OrganizationID,
	)
	var i CustomRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.IsDefault,
		&i.DefaultScopeMode,
		&i.DefaultAllowedInstanceIds,
		&i.DefaultAllowedPhoneNumbers,
		&i.CanViewUnmaskedPhone,
	)
	return i, err
}
