// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserPermissionOverrides = `-- name: DeleteUserPermissionOverrides :exec
DELETE FROM user_permission_overrides
WHERE organization_id = $1::uuid
  AND user_id = $2::uuid
`

type DeleteUserPermissionOverridesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserPermissionOverrides(ctx context.Context, arg DeleteUserPermissionOverridesParams) error {
	_, err := q.db.Exec(ctx, deleteUserPermissionOverrides, arg.OrganizationID, arg.UserID)
	return err
}

const getUserVisibilityRule = `-- name: GetUserVisibilityRule :one
SELECT id, organization_id, user_id, scope_mode, allowed_instance_ids, allowed_phone_numbers,
       inherit_role_scope, can_view_unmasked_phone, created_at, updated_at
FROM user_contact_visibility_rules
WHERE organization_id = $1::uuid
  AND user_id = $2::uuid
`

type GetUserVisibilityRuleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserVisibilityRule(ctx context.Context, arg GetUserVisibilityRuleParams) (UserContactVisibilityRule, error) {
	row := q.db.QueryRow(ctx, getUserVisibilityRule, arg.OrganizationID, arg.UserID)
	var i UserContactVisibilityRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ScopeMode,
		&i.AllowedInstanceIds,
		&i.AllowedPhoneNumbers,
		&i.InheritRoleScope,
		&i.CanViewUnmaskedPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserPermissionOverride = `-- name: InsertUserPermissionOverride :exec
INSERT INTO user_permission_overrides (
  organization_id,
  user_id,
  permission_key,
  mode
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::text
)
ON CONFLICT (organization_id, user_id, permission_key)
DO UPDATE SET mode = EXCLUDED.mode, updated_at = now()
`

type InsertUserPermissionOverrideParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	PermissionKey  string    `json:"permission_key"`
	Mode           string    `json:"mode"`
}

func (q *Queries) InsertUserPermissionOverride(ctx context.Context, arg InsertUserPermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, insertUserPermissionOverride,
		arg.OrganizationID,
		arg.UserID,
		arg.PermissionKey,
		arg.Mode,
	)
	return err
}

const listUserPermissionOverrides = `-- name: ListUserPermissionOverrides :many
SELECT permission_key, mode
FROM user_permission_overrides
WHERE organization_id = $1::uuid
  AND user_id = $2::uuid
ORDER BY permission_key ASC
`

type ListUserPermissionOverridesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type ListUserPermissionOverridesRow struct {
	PermissionKey string `json:"permission_key"`
	Mode          string `json:"mode"`
}

func (q *Queries) ListUserPermissionOverrides(ctx context.Context, arg ListUserPermissionOverridesParams) ([]ListUserPermissionOverridesRow, error) {
	rows, err := q.db.Query(ctx, listUserPermissionOverrides, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPermissionOverridesRow
	for rows.Next() {
		var i ListUserPermissionOverridesRow
		if err := rows.Scan(&i.PermissionKey, &i.Mode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT
  u.id,
  u.email,
  u.full_name,
  u.avatar_url,
  u.is_active,
  u.availability_status,
  u.settings,
  uo.role_id,
  r.name AS role_name
FROM users u
JOIN user_organizations uo ON uo.user_id = u.id
JOIN custom_roles r ON r.id = uo.role_id
WHERE uo.organization_id = $1::uuid
  AND u.deleted_at IS NULL
  AND uo.deleted_at IS NULL
  AND r.deleted_at IS NULL
ORDER BY u.full_name ASC
`

type ListUsersByOrganizationRow struct {
	ID                 uuid.UUID   `json:"id"`
	Email              string      `json:"email"`
	FullName           string      `json:"full_name"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	IsActive           bool        `json:"is_active"`
	AvailabilityStatus string      `json:"availability_status"`
	Settings           []byte      `json:"settings"`
	RoleID             uuid.UUID   `json:"role_id"`
	RoleName           string      `json:"role_name"`
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByOrganizationRow
	for rows.Next() {
		var i ListUsersByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.IsActive,
			&i.AvailabilityStatus,
			&i.Settings,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserVisibilityRule = `-- name: UpsertUserVisibilityRule :one
INSERT INTO user_contact_visibility_rules (
  organization_id,
  user_id,
  scope_mode,
  allowed_instance_ids,
  allowed_phone_numbers,
  inherit_role_scope,
  can_view_unmasked_phone
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::jsonb,
  $5::jsonb,
  $6::bool,
  $7::bool
)
ON CONFLICT (organization_id, user_id)
DO UPDATE SET
  scope_mode = EXCLUDED.scope_mode,
  allowed_instance_ids = EXCLUDED.allowed_instance_ids,
  allowed_phone_numbers = EXCLUDED.allowed_phone_numbers,
  inherit_role_scope = EXCLUDED.inherit_role_scope,
  can_view_unmasked_phone = EXCLUDED.can_view_unmasked_phone,
  updated_at = now()
RETURNING id, organization_id, user_id, scope_mode, allowed_instance_ids, allowed_phone_numbers,
          inherit_role_scope, can_view_unmasked_phone, created_at, updated_at
`

type UpsertUserVisibilityRuleParams struct {
	OrganizationID       uuid.UUID `json:"organization_id"`
	UserID               uuid.UUID `json:"user_id"`
	ScopeMode            string    `json:"scope_mode"`
	AllowedInstanceIds   []byte    `json:"allowed_instance_ids"`
	AllowedPhoneNumbers  []byte    `json:"allowed_phone_numbers"`
	InheritRoleScope     bool      `json:"inherit_role_scope"`
	CanViewUnmaskedPhone bool      `json:"can_view_unmasked_phone"`
}

func (q *Queries) UpsertUserVisibilityRule(ctx context.Context, arg UpsertUserVisibilityRuleParams) (UserContactVisibilityRule, error) {
	row := q.db.QueryRow(ctx, upsertUserVisibilityRule,
		arg.OrganizationID,
		arg.UserID,
		arg.ScopeMode,
		arg.AllowedInstanceIds,
		arg.AllowedPhoneNumbers,
		arg.InheritRoleScope,
		arg.CanViewUnmaskedPhone,
	)
	var i UserContactVisibilityRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ScopeMode,
		&i.AllowedInstanceIds,
		&i.AllowedPhoneNumbers,
		&i.InheritRoleScope,
		&i.CanViewUnmaskedPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
